force-app/main/default/objects/Product2/fields/GYNCF_Average_Rating__c.field-meta.xml
<CustomField>
    <fullName>GYNCF_Average_Rating__c</fullName>
    <label>Overall Rating</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/GYNCF_Price__c.field-meta.xml
<CustomField>
    <fullName>GYNCF_Price__c</fullName>
    <label>Price</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/GYNCF_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>GYNCF_Product_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Category</label>
    <referenceTo>GYNCO_Product_Category__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/GYNCF_Tags__c.field-meta.xml
<CustomField>
    <fullName>GYNCF_Tags__c</fullName>
    <label>Tags</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/GYNF_Availability__c.field-meta.xml
<CustomField>
    <fullName>GYNF_Availability__c</fullName>
    <label>Availability</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GYNC_SearchController.cls
public with sharing class GYNC_SearchController {
    @AuraEnabled
    public static List <Product2> searchData() {
   List<Product2> prodList = [SELECT Id,Name,ProductCode,GYNF_Availability__c,GYNCF_Price__c,GYNCF_Product_Category__r.Name,GYNCF_Average_Rating__c,GYNCF_Tags__c from Product2 
                              WHERE GYNCF_Product_Category__c != null LIMIT 50000];
    // System.debug(prodList);
//    List<Product2> prodList = [SELECT Id,GYNCF_Product_Category__r.Name,Name FROM product2];
    return prodList;
          
    } 
    @AuraEnabled
    public static List <Product2> priceLowToHigh() {
        List<Product2> retValue = [SELECT Id, Name,ProductCode,GYNF_Availability__c,GYNCF_Price__c,GYNCF_Product_Category__r.name,GYNCF_Average_Rating__c from Product2 ORDER BY GYNCF_Price__c ASC ];
        return retValue;      
    }
    @AuraEnabled
    public static List <Product2> priceHighToLow() {
        List<Product2> retValue = [SELECT Id, Name,ProductCode,GYNF_Availability__c,GYNCF_Price__c,GYNCF_Product_Category__r.name,GYNCF_Average_Rating__c from Product2 ORDER BY GYNCF_Price__c DESC];
        return retValue;      
    }
    @AuraEnabled
    public static List <Product2> popularityLowToHigh() {
        List<Product2> retValue = [SELECT Id, Name,ProductCode,GYNF_Availability__c,GYNCF_Price__c,GYNCF_Product_Category__r.name,GYNCF_Average_Rating__c from Product2 ORDER BY GYNCF_Average_Rating__c ASC];
        return retValue;      
    }
    @AuraEnabled
    public static List <Product2> popularityHighToLow() {
        List<Product2> retValue = [SELECT Id, Name,ProductCode,GYNF_Availability__c,GYNCF_Price__c,GYNCF_Product_Category__r.name,GYNCF_Average_Rating__c from Product2 ORDER BY GYNCF_Average_Rating__c DESC];
        return retValue;      
    }   
    @AuraEnabled
    public static List<Product2> sliderProducts(decimal limitFromSlider){
        Product2 test=[select GYNCF_Price__c from Product2 where GYNCF_Price__c <= :limitfromSlider];
     //  integer value= integer.Parse(limitfromSlider,NumberStyles.Currency);
     //  limitFromSlider= [select GYNCF_Price__c from Product2];
      System.debug(limitFromSlider);
     //  integer test= integer.valueOf(limitFromSlider);
        System.debug(test);
        return [SELECT Id, Name,ProductCode,GYNF_Availability__c,GYNCF_Price__c,GYNCF_Product_Category__r.name,GYNCF_Average_Rating__c from Product2 where GYNCF_Price__c<: limitFromSlider ];
    }

}